### ISSUE TITLE
Quoted Message sender's name ERROR/BUG

### ISSUE THREAD

**Issue by animeworld0310** [Renks/WhatsAppViewer#2]
![Screenshot_2023-01-18-19-02-29-95_6012fa4d4ddec268fc5c7112cbb265e7](https://user-images.githubusercontent.com/73987648/213185966-1f0458d1-639b-4c18-b158-f178a6fc8d1c.jpg)

Like as shown in above image which is taken from WhatsApp if the quoted message was from me then it displays You and if it's from the other person then it displays their profile name but in the project 
The bug or error is that in sender's name of quoted Message it shows only profile name even if the quoted message was sent by me

**Comment by Renks** [comment]
Hi animeworld,

I'm terribly sorry to inform you that the project's no longer being maintained as I've been too busy with other stuff lately. Thanks for showing interest in it tho :)

But but but...... on second thought can you post a screenshot showing "what its supposed to look like vs what it currently looks like". If it isn't too big of a fix I might just do it.

> ![Screenshot_2023-01-18-19-02-29-95_6012fa4d4ddec268fc5c7112cbb265e7](https://user-images.githubusercontent.com/73987648/213185966-1f0458d1-639b-4c18-b158-f178a6fc8d1c.jpg)
> 
> Like as shown in above image which is taken from WhatsApp if the quoted message was from me then it displays You and if it's from the other person then it displays their profile name but in the project The bug or error is that in sender's name of quoted Message it shows only profile name even if the quoted message was sent by me

**Comment by animeworld0310** [comment]
![WhatsApp Image 2023-01-20 at 20 18 25](https://user-images.githubusercontent.com/73987648/213727642-17a757bf-13ba-48e7-8e32-d40681efcc11.jpg)
Hello Ranks 
Thanks For responding to my message 
To fix this you will hardly require 10 min as I don't know much about javascript so I'm unable to fix it 
It is the line number 284 in the javascript

How it should look vs How it looks

**Comment by Renks** [comment]
Hi animeworld,
It's fixed, you should be able to see the correct sender name now.

**Comment by animeworld0310** [comment]
> Hi animeworld, It's fixed, you should be able to see the correct sender name now.

Thanks bro Thank you so much 

But just a small one more request please do something to change its color also please

**Comment by Renks** [comment]
> > Hi animeworld, It's fixed, you should be able to see the correct sender name now.
> 
> Thanks bro Thank you so much
> 
> But just a small one more request please do something to change its color also please

Maybe in future 🙂
