### ISSUE TITLE
Code for Changing Color of Quoted Sender Name and Tiny Bar

### ISSUE THREAD

**Issue by animeworld0310** [Renks/WhatsAppViewer#4]
I don't know how to make pull request so I'm just adding the code here.

#Whatsapp CSS
Edit 1:
https://github.com/Renks/WhatsAppViewer/blob/6411ccd3a125be07248742f6c5be7ecef61de83e/WhatsAppViewer/static/css/whatsapp.css#L344
> Change This:            .color-1 {color: #06cf9c!important;}
> To This:                     .color-1 {color: #ef6130 !important;}

Edit 2:
https://github.com/Renks/WhatsAppViewer/blob/6411ccd3a125be07248742f6c5be7ecef61de83e/WhatsAppViewer/static/css/whatsapp.css#L370
> Change This:            .bg-color-1{background-color: #06cf9c!important;}
> To This:                     .bg-color-1{background-color: #ef6130;}

#Javascript
Edit 3: 
https://github.com/Renks/WhatsAppViewer/blob/6411ccd3a125be07248742f6c5be7ecef61de83e/WhatsAppViewer/static/js/script.js#L289

> Add the given code below line 289

   if (msg['message_quoted_from_me']) {
                    tmpMsgTxtClone.querySelector("span[data-temp-id='sender-name']").style.color = "#06cf9c";
                    tmpMsgTxtClone.querySelector("span[class='bg-color-1 tiny-bar']").style.backgroundColor = "#06cf9c";
                }

**Comment by Renks** [comment]
Thanks for the code, I'll add it later myself.
But please don't open anymore issues needlessly.

**Comment by animeworld0310** [comment]
Okh I just opened it coz I didn't knew how to tell you the code if you had
contacted me on telegram then I would have just sent it there instead of
opening new issue

**Comment by Renks** [comment]
> Okh I just opened it coz I didn't knew how to tell you the code if you had contacted me on telegram then I would have just sent it there instead of opening new issue

Code updated.

**Comment by animeworld0310** [comment]
👍🙂
